spring:
  application:
    name: batch-audit-system
  
  profiles:
    active: local
  
  # Oracle Database Configuration
  datasource:
    url: ${ORACLE_DB_URL:jdbc:oracle:thin:@//localhost:1521/ORCLPDB1}
    username: ${ORACLE_DB_USERNAME:cm3int}
    password: ${ORACLE_DB_PASSWORD:password}
    driver-class-name: oracle.jdbc.OracleDriver
    
    # HikariCP Connection Pool Configuration
    hikari:
      pool-name: AuditHikariPool
      maximum-pool-size: ${audit.database.connection-pool-size}
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 1800000
      connection-timeout: 20000
      leak-detection-threshold: 60000
      connection-test-query: SELECT 1 FROM DUAL
      auto-commit: false
      
  # JdbcTemplate Configuration
  jdbc:
    template:
      fetch-size: 100
      max-rows: 0
      query-timeout: 30
  
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle19cDialect
        format_sql: true
        jdbc:
          batch_size: ${audit.database.batch-size}
          time_zone: UTC
    show-sql: false
  
  # Liquibase Configuration
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
    drop-first: false
    contexts: ${spring.profiles.active}
    default-schema: ${ORACLE_DB_USERNAME:cm3int}
    liquibase-schema: ${ORACLE_DB_USERNAME:cm3int}
    database-change-log-table: DATABASECHANGELOG
    database-change-log-lock-table: DATABASECHANGELOGLOCK

# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /audit

# Management and Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

# SpringDoc OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    try-it-out-enabled: true
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true
    show-extensions: true
    show-common-extensions: true
  packages-to-scan: com.company.audit.controller
  paths-to-match: /api/**

# Audit System Configuration
audit:
  database:
    batch-size: 100
    connection-pool-size: 10
  retention:
    days: 365
  reconciliation:
    auto-generate: true
    schedule: "0 0 6 * * ?"
  dashboard:
    page-size: 50
    max-export-records: 10000

# Logging Configuration
logging:
  level:
    com.company.audit: INFO
    org.springframework.jdbc: DEBUG
    liquibase: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"